name: FactionsPro
author: Tethered_, edited by VMPE Development Team
description: A Extended Factions plugin.
version: 2.0.0-BETA
main: FactionsPro\FactionMain
api: [3.0.0-ALPHA10]
softdepend: ["PureChat", "AntiSpamPro"]
commands:
  f:
    description: Faction commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
