---
name: FactionsPro
author: Tethered_
description: Lets Bring Back FactionsPro The Better Way!
version: 1.1
main: FactionsPro\FactionMain
api:
- 3.0.0-ALPHA10
commands:
  f:
    permission: f.command
permissions:
  f.command:
    default: true
...
